<?php
/**
 * The default template part for the product variants
 * in the content-product template part's
 * color variant element
 *
 * @since 1.0.0
 * @version 1.0.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy this file's
 * content to the exchange/content-product/elements
 * directory located in your theme.
*/
?>
<?php do_action( 'it_exchange_content_product_before_variant_element' ); ?>
<div class="it-variant-options it-variant-hex-options">
	<?php do_action( 'it_exchange_content_product_begin_variant_element' ); ?>
	<div class="it-variant-title">Color Variants</div>
	<ul class="it-variant-hex-list">
		<?php while( it_exchange( 'variant', 'values' ) ) : ?>
		<li class="it-variant-color">
			<div class="it-variant-color-inner" style="height:55px;width:55px;background:<?php it_exchange( 'variant-value', 'color' ); ?>"></div>
		</li>
		<?php endwhile; ?>
	</ul>
	<?php do_action( 'it_exchange_content_product_end_variant_element' ); ?>
</div>
<?php do_action( 'it_exchange_content_product_after_variants_element' ); ?>
