<?php
/**
 * The default template part for the product variants
 * in the content-product template part's
 * product-info loop.
 *
 * @since 1.0.0
 * @version 1.0.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy this file's
 * content to the exchange/content-product/elements
 * directory located in your theme.
*/
?>
<?php if ( it_exchange( 'product', 'has-variants' ) ) : ?>
	<?php do_action( 'it_exchange_content_product_before_variants_element' ); ?>
	<div class="it-exchange-product-variants">
		<?php do_action( 'it_exchange_content_product_begin_variants_element' ); ?>
		<?php while( it_exchange( 'product', 'variants' ) ) :  ?>
			<?php if ( it_exchange( 'variant', 'has-values' ) ) : ?>
				<?php it_exchange_get_template_part( 'content', 'product/elements/' . it_exchange( 'variant', 'get-type' ) . '-variant' ); ?>
			<?php endif; ?>
		<?php endwhile; ?>
		<?php do_action( 'it_exchange_content_product_end_variants_element' ); ?>
	</div>
	<?php do_action( 'it_exchange_content_product_after_variants_element' ); ?>
<?php endif; ?>
