<?php
/**
 * The default template part for the product variants
 * in the content-product template part's
 * product-info loop.
 *
 * @since 1.0.0
 * @version 1.0.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy this file's
 * content to the exchange/content-product/elements
 * directory located in your theme.
*/
?>
<?php //if ( it_exchange( 'product', 'has-base-price' ) ) : ?>
	<?php do_action( 'it_exchange_content_product_before_variants_element' ); ?>
	<div class="it-exchange-product-variants">
		<?php do_action( 'it_exchange_content_product_begin_variants_element' ); ?>
		<!-- Start HARDCODED DIVS for Ty -->
		<div class="it-variant-options it-variant-select-options">
			<div class="it-variant-title">Dropdown Variants</div>
			<select class="it-variant-select">
				<option>Select Option One</option>
				<option selected>Select Option Two</option>
				<option>Select Option Three</option>
			</select>
		</div>

		<div class="it-variant-options it-variant-radio-options">
			<div class="vit-ariant-title">Radio Variants</div>
			<ul class="it-variant-radios">
				<li><label><input type="radio" class="it-variant-options" checked/> Radio Option One</label></li>
				<li><label><input type="radio" class="it-variant-options" /> Radio Option Two</label></li>
				<li><label><input type="radio" class="it-variant-options" /> Radio Option Three</label></li>
			</ul>
		</div>

		<div class="it-variant-options it-variant-image-options">
			<div class="it-variant-title">Image Variants</div>
			<ul class="it-variant-image-list">
				<li class="it-variant-image">
					<img src="http://placehold.it/55x55" />
				</li>
				<li class="it-variant-image selected">
					<img src="http://placehold.it/55x55" />
				</li>
				<li class="it-variant-image">
					<img src="http://placehold.it/55x55" />
				</li>
			</ul>
		</div>

		<div class="it-variant-options it-variant-hex-options">
			<div class="it-variant-title">Color Variants</div>
			<ul class="it-variant-hex-list">
				<li class="it-variant-color">
					<div class="it-variant-color-inner" style="height:55px;width:55px;background:#F1FFDE"></div>
				</li>
				<li class="it-variant-color selected">
					<div class="it-variant-color-inner" style="height:55px;width:55px;background:#0082CA"></div>
				</li>
				<li class="it-variant-color">
					<div class="it-variant-color-inner" style="height:55px;width:55px;background:#334940"></div>
				</li>
			</ul>
		</div>
		<!-- END HARDCODED DIVS for Ty -->
		<?php do_action( 'it_exchange_content_product_end_variants_element' ); ?>
	</div>
	<?php do_action( 'it_exchange_content_product_after_variants_element' ); ?>
<?php //endif; ?>
